#MEDIDAS
ANCHO_VENTANA=1500
ALTO_VENTANA=800

MAPA_ANCHO = 1500  
MAPA_ALTO = 800   
UI_ALTO = 100     # Altura para el panel de botones/HUD

VENTANA_ANCHO_TOTAL = MAPA_ANCHO
VENTANA_ALTO_TOTAL = MAPA_ALTO + UI_ALTO

#FACTORES
FACTOR=0.2


#COLORES
COLOR_NEGRO=(0,120,0)
COLOR_VERDE=(0,225,0)
COLOR_ROJO=(225,0,0)


#CUADRÍCULA
CANTIDAD_I=50
CANTIDAD_J=50

CELDA_ANCHO = MAPA_ANCHO / CANTIDAD_I
CELDA_ALTO = MAPA_ALTO / CANTIDAD_J

